---
output:
   html_document:
    self_contained: true
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r setup}

# Freeze date
freeze_date <- as.Date("2025-06-30")

# Load packages
library(DBI) # Connecting to database
library(tidyverse) # Data wrangling
library(flextable) # Pretty table

# Connect to PAN database
con <- dbConnect(RPostgres::Postgres(),
                 user = Sys.getenv("user")
                 , password = Sys.getenv("password")
                 , dbname = Sys.getenv("dbname")
                 , host = Sys.getenv("host")
                 , port = Sys.getenv("port")
                 , sslrootcert = 'global-bundle.pem'
)

source("get_participant_ids.R")
freeze_ids <- get_participant_ids(freeze_date)

```

## Carotid Ultrasound Table

```{r pull-data}

p2_carotid_ultrasound_velocity <- dbReadTable(con, "p2_carotid_ultrasound_velocity")

```

```{r wrangle-data}

ultrasound_table_dat <- 
  p2_carotid_ultrasound_velocity %>%
  right_join(data.frame(hml_id = freeze_ids), by = "hml_id") %>%
  select(-c(hml_id, redcap_id, mindcrowd_id, site, scan_date, notes)) %>%
  # Calculate missing data
  mutate(across(everything(), ~ifelse(is.na(.), 1, 0))) %>%
  mutate(sum_missing = rowSums(select(., everything())),
         complete_data = ifelse(sum_missing == 0, 1, 0),
         # velocity variables
         velocity = rowSums(select(., c(rcca_pws, rcca_pwd, r_sd_ratio, r_ri, 
                                        rbif_pws, rbif_pwd, rbif_sd_ratio, 
                                        rbif_ri, rica_pws, rica_pwd, rica_sd_ratio, 
                                        rica_ri, reca_pws, reca_pwd, reca_sd_ratio, 
                                        reca_ri, lcca_pws, lcca_pwd, l_sd_ratio, 
                                        l_ri, lbif_pws, lbif_pwd, lbif_sd_ratio, 
                                        lbif_ri, lica_pws, lica_pwd, lica_sd_ratio, 
                                        lica_ri, leca_pws, leca_pwd, leca_sd_ratio, 
                                        leca_ri))), 
         complete_velocity = ifelse(velocity == 0, 1, 0),
         # IMT variables
         imt = rowSums(select(., c(rccanwmx, rccanwmn, rccafwmx, rccafwmn, rbifnwmx, 
                                   rbifnwmn, rbiffwmx, rbiffwmn, ricanwmx, ricanwmn, 
                                   ricafwmx, ricafwmn, lccanwmx, lccanwmn, lccafwmx, 
                                   lccafwmn, lbifnwmx, lbifnwmn, lbiffwmx, lbiffwmn, 
                                   licanwmx, licanwmn, licafwmx, licafwmn))),
         complete_imt = ifelse(imt == 0, 1, 0),) %>%
  summarise(sum_velocity = sum(complete_velocity),
            sum_imt = sum(complete_imt) #, sum_complete = sum(complete_data)
            ) %>%
  pivot_longer(cols = everything()) %>%
  # Format percent for table
  mutate(value = paste0(value, " (", round(value/length(freeze_ids) * 100, 2), "%)"),
         name = case_when(#name == "sum_complete" ~ "All Data",
                          name == "sum_velocity" ~ "Velocity Data",
                          name == "sum_imt" ~ "Intima-Media Thickness (IMT) Data"))

```

```{r create-table}

ultrasound_table_dat %>%
  flextable() %>%
  set_header_labels(name = "", value = paste0("Available \n (N=", length(freeze_ids),")")) %>%
  autofit()

```