---
output:
   html_document:
    self_contained: true
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r setup}

# Freeze date
freeze_date <- as.Date("2025-06-30")

# Load packages
library(DBI) # Connecting to database
library(tidyverse) # Data wrangling
library(flextable) # Pretty table

# Connect to PAN database
con <- dbConnect(RPostgres::Postgres(),
                 user = Sys.getenv("user")
                 , password = Sys.getenv("password")
                 , dbname = Sys.getenv("dbname")
                 , host = Sys.getenv("host")
                 , port = Sys.getenv("port")
                 , sslrootcert = 'global-bundle.pem'
)

source("get_participant_ids.R")
freeze_ids <- get_participant_ids(freeze_date)

```

## Neuropsych Batteries Table

```{r pull-data}

p2_redcap_cognitive_function_avlt <- dbGetQuery(con, "SELECT hml_id, avlt_complete FROM p2_redcap_cognitive_function_avlt")

p2_redcap_cognitive_function_moca <- dbGetQuery(con, "SELECT hml_id, moca_complete FROM p2_redcap_cognitive_function_moca")

p2_redcap_cognitive_function_naart <- dbGetQuery(con, "SELECT hml_id, naart_complete FROM p2_redcap_cognitive_function_naart")

```

```{r wrangle-data}

cognitive_function_table_dat <- data.frame(hml_id = freeze_ids) %>%
  left_join(p2_redcap_cognitive_function_avlt, by = "hml_id") %>%
  left_join(p2_redcap_cognitive_function_moca, by = "hml_id") %>%
  left_join(p2_redcap_cognitive_function_naart, by = "hml_id") %>%
  select(-hml_id) %>%
  mutate(across(everything(), ~ifelse(is.na(.), 0, .))) %>%
  summarise(avlt = sum(avlt_complete),
            moca = sum(moca_complete),
            naart = sum(naart_complete)) %>%
  pivot_longer(everything()) %>%
  mutate(value = paste0(value, " (", round(value/length(freeze_ids) * 100, 2), "%)"),
         name = str_to_upper(name),
         name = ifelse(name == "MOCA", "MoCA", name))

```

```{r create-table}

cognitive_function_table_dat %>%
  flextable() %>%
  set_header_labels(name = "", value = paste0("Available \n (N=", length(freeze_ids),")")) %>%
  autofit()

```